### PR TITLE
Added travis ci support

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by amilajack** [comment]
🎉 Last step is to enable tests at https://travis-ci.org

**Comment by marcoscaceres** [comment]
Done! (I think)

**Comment by marcoscaceres** [comment]
I sent a test payload, but didn't see it show up yet... checking further...

**Comment by marcoscaceres** [comment]
Ok cool, it's working... but failing... so that's a start! 
https://travis-ci.org/extensibleweb/webidl.js

**Comment by amilajack** [comment]
Seems like some kind of network error is causing the error.

**Pull request merged**
